/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Rust API
 * This is the template for the Rust API
 * OpenAPI spec version: 0.1.0
 */

export type AuthType = (typeof AuthType)[keyof typeof AuthType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthType = {
  Oidc: "Oidc",
  BuildIn: "BuildIn",
} as const;
