/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Rust API
 * This is the template for the Rust API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthProtocol } from "./authProtocol";

export interface AuthStatus {
  can_register: boolean;
  enabled_protocol: AuthProtocol[];
}
