/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Rust API
 * This is the template for the Rust API
 * OpenAPI spec version: 0.1.0
 */

export type LoginStatus = (typeof LoginStatus)[keyof typeof LoginStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginStatus = {
  OtpStep: "OtpStep",
  RefreshStep: "RefreshStep",
} as const;
