/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Rust API
 * This is the template for the Rust API
 * OpenAPI spec version: 0.1.0
 */

export interface PublicUser {
  id: string;
  nom: string;
  prenom: string;
}
