/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Rust API
 * This is the template for the Rust API
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  created_at: string;
  email: string;
  id: string;
  nom: string;
  otp_enabled: boolean;
  prenom: string;
  updated_at: string;
}
